### ISSUE TITLE
Keyboard compatibility

### ISSUE THREAD

**Issue by Likver** [osudroid/osu-droid#111]
Can you make a option for play with keyboard please? I need it

**Comment by MoDyPL** [comment]
U can use octopus app on google play store

**Comment by Likver** [comment]
> U can use octopus app on google play store

I can't, Octopus dont run this game, i dont know why

**Comment by rosenishere** [comment]
Even if you can, native support is always better. I vouch.

**Comment by Likver** [comment]
> Even if you can, native support is always better. I vouch.

- You mean connect it via OTG? If it is, i dont have OTG, my phone sucks

**Comment by rosenishere** [comment]
yeah exactly what they meant

**Comment by HeyYoWhatBro** [comment]
> > U can use octopus app on google play store
> 
> I can't, Octopus dont run this game, i dont know why

There support but by old version of octopus

**Comment by HeyYoWhatBro** [comment]
> > Even if you can, native support is always better. I vouch.
> 
> * You mean connect it via OTG? If it is, i dont have OTG, my phone sucks

But input delay will possible use otg

**Comment by Beyley** [comment]
> > > U can use octopus app on google play store
> > 
> > 
> > I can't, Octopus dont run this game, i dont know why
> 
> There support but by old version of octopus

Old versions generally cant be easily acquired, and when you do go searching for them its usually from an untrustworthy source

**Comment by Beyley** [comment]
> > > Even if you can, native support is always better. I vouch.
> > 
> > 
> > 
> > * You mean connect it via OTG? If it is, i dont have OTG, my phone sucks
> 
> But input delay will possible use otg

Input delay (like with the touchscreen too) will vary depending on the device, with some it might be better then touchscreen, but with other devices it might be worse

**Comment by Rian8337** [comment]
From the developers' standpoint, the main problem with adding keyboard and mouse support is handling mouse and keyboard events. This must be done in a way such that it supports both gameplay and replay, both with or without either of those hardware. Don't get me wrong, mouse and keyboard support is awesome and is something that has been requested by multiple players in the game's related communities (QQ, Discord, you name it), however with the way things are structured as of now, this is *very* hard to do, and not worth the development cost considering most players play with touchscreen.

The game only recognizes 1 input type (which is touch). Changing it will require a rework to replay cursor movement and input handling. This adds another layer of complexity as we'd also need to decide what to do with touchscreen. Due to that, the easiest and most straightforward way I can think of to work around the problem is to map keyboard/mouse events to touch such that the game picks it up as a touch event.

The main problem with the above approach is mapping mouse and keyboard press events to whatever position in the screen can make you accidentally press a note while playing. In my opinion, this is a very bad UX, making this approach not worth it. Trying to work around this also introduces another problem and (yet) more considerations for discussion.

With that being said, I don't think this will be supported. Apologies.
