### ISSUE TITLE
Beatmaps may duplicate at certain occasions

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#328]
This is a bug that has happened to multiple players, yet bizarre as the root cause of the problem is still unknown.

This seems to be a problem at caching operation, as when one of the duplicates is deleted from song selection menu, both beatmaps will be deleted. Additionally, once the player reloads the beatmap cache, the problem is gone, but it can still come back at certain occasions.

Despite being reported multiple times, little is known about this bug. Anyone experiencing the bug or seeing it first-hand can comment more details on this issue.

This is a report that I received from a player. Note that downloading the map from Chimu does not always trigger the problem, otherwise I would have more information to work with. All beatmap cache loading operations navigate towards `LibraryManager.updateLibrary()`.
> All of the maps i have are duplicated and now there is 2 of every map. I started having this problem after i tried the new built in map downloader function, Chimu.moe. After i downloaded a map, it caused all of my maps to be duplicated and if i try to delete one of the copies, both will be deleted.
![image](https://github.com/osudroid/osu-droid/assets/52914632/ae395ad5-f271-4fd5-9357-1f27ac55f67c)

**Comment by Saiaku27** [comment]
i encountered this bug and and after experimenting i also know how to recreate this bug but While trying to Recreate this bug I encountered another bug which is similar to this one(like having duplicate maps) But Also different, idk What is important info so ill just Write everything that happened so sorry in advance and please don't mind it getting cluttery.


recreate method:
double/triple clicking(with 2/3 different fingers at same time) the "solo" button , this same method creates 2 different but slightly similar(?) bugs
1. this will open the Maps menu but the game will crash with No visible maps on screen as Crash message is desplayed. after Reopening the game all maps are doubled and Don't solve unless beatmap cache is cleared from library settings, deleting 1 beatmap deletes the other copy too.
![duplicate normal crash](https://github.com/user-attachments/assets/1edac303-7614-4366-b721-d81534939240)
![duplicate normal](https://github.com/user-attachments/assets/8e328856-3ecc-4a40-90bc-4b3f945190e1)
![duplicate normal 2](https://github.com/user-attachments/assets/e71f0be8-7742-44b5-9e2f-f45f468e2c67)


2. in another time, clicking solo this specific way the inbuilt beatmap downloader opens on its own(i checked again , I didn't missclick the beatmap downloader icon either), after exiting the beatmap downloader,game directly shows maps menu with only 1 or 2 maps visible, it only shows those 1/2 maps even after restart unless map cache is cleared. when there were only 2 maps showing in this bug i tried the recreate method once again and After crash on reopening the only showing 2 maps were also doubled, idk If these 2bugs are related so i listed them both, Sorry if they're not same.
![map downloader duplicate](https://github.com/user-attachments/assets/8c6b2b4f-da15-45eb-b0d8-bf5f7eb649e3)
![map downloader duplicate 2](https://github.com/user-attachments/assets/8fc518ac-0ff8-4e3d-a262-339ae08f158f)



so here's wht happened 
so because i was having internet issues, i failed to log in so i opened the "Options" button and left the options so the game can retry my login, While it was logging in I tried entering the game and clicked the "solo" button But while it responded, like with making clicking sound and glow etc but it didn't do anything like it was stuck, so i spammed the Solo button after a while the game let me in but it crashed, after Reopening the double maps was there, i thought it was probably related to Spam clicking solo button so i tried that but that solo button stuck thing didn't happen anymore so i tried double clicking the button instead and The beatmap downloader bug mentioned above happened instead, i Once again Tried double clicking solo button(while still on beatmap downloader bug) and this time the only showing 2 maps on menu also doubled.


i crashed the gane many times so there's log file too, all the crashes todays date are about these 2 bugs , the log file is big so ill try posting it in this message's repply

**Comment by Saiaku27** [comment]
errorlog file
[errorlog.txt](https://github.com/user-attachments/files/16500498/errorlog.txt)

**Comment by Saiaku27** [comment]
i cant edit images so here's update,  After just trying this method again on Already doubled bug, the doubled maps doubled again,now there are 4 same maps of each map
![Screenshot_20240805_222637](https://github.com/user-attachments/assets/99e97dd9-97e5-4e44-a430-53ffe7efec99)

**Comment by Saiaku27** [comment]
sorry im back😅, it seems the bug can be Created even in "play" button if used 3 fingers simultaneously and lifting the fingers, those acts as 3 superfast/instant touch on the button and creates the bug.On side note Using this method on "multi" button , that creates a brand new Bug but maybe i shouldn't talk about that in this thread, you Guys try and check out that bug too👍😅
