### ISSUE TITLE
Hit circle game objects are pooled too early

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#347]
As the title says. This causes its animation to not finish properly after judgement, and its state will remain until it is reused, as shown in the video below.

https://github.com/osudroid/osu-droid/assets/52914632/2dd3ce8a-c6c1-4267-be05-028c9377cf1e

**Comment by Reco1I** [comment]
https://github.com/osudroid/osu-droid/blob/master/src%2Fru%2Fnsu%2Fccfit%2Fzuev%2Fosu%2Fgame%2FSpritePool.java#L33-L54

The issue is here exactly. The sprite gets reset before using it back, this is indeed caused by what the title says.

There's a thing with `SpritePool`, I personally believe that it's not necessary since hit objects are already pooled by `GameObjectPool`.
